# Generated by Django 2.2.2 on 2019-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190621_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_publish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
